---
# tasks file for r_install_packages
- name: "install packages"
  tags:
    - install_packages

  block:
    - name: "debug"
      ansible.builtin.debug:
        msg: "{{ item.packages }}"
      loop: "{{ lookup('file', 'data/packages/install.yaml') }}"

  rescue:
    - name: "role {{ ansible_role_name }} failed"
      ansible.builtin.fail:
        msg: "error: during copy do files to {{ regular_home }}"

